INSERT INTO players (name) VALUES ('Новак Джокович');
INSERT INTO players (name) VALUES ('Рафаэль Надаль');
INSERT INTO players (name) VALUES ('Роджер Федерер');
INSERT INTO players (name) VALUES ('Энди Маррей');
INSERT INTO players (name) VALUES ('Стэн Вавринка');
INSERT INTO players (name) VALUES ('Хуан Мартин дель Потро');
INSERT INTO players (name) VALUES ('Марин Чилич');
INSERT INTO players (name) VALUES ('Кеи Нисикори');
INSERT INTO players (name) VALUES ('Доминик Тим');
INSERT INTO players (name) VALUES ('Александр Зверев');
INSERT INTO players (name) VALUES ('Мартин Иден');
INSERT INTO players (name) VALUES ('Лютый тип');
INSERT INTO players (name) VALUES ('Нереально жесткий');

INSERT INTO matches (player1, player2, winner) VALUES (1, 2, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 4, 3);
INSERT INTO matches (player1, player2, winner) VALUES (5, 6, 5);
INSERT INTO matches (player1, player2, winner) VALUES (7, 8, 8);
INSERT INTO matches (player1, player2, winner) VALUES (9, 10, 9);
INSERT INTO matches (player1, player2, winner) VALUES (1, 3, 1);
INSERT INTO matches (player1, player2, winner) VALUES (2, 4, 2);
INSERT INTO matches (player1, player2, winner) VALUES (5, 7, 7);
INSERT INTO matches (player1, player2, winner) VALUES (6, 8, 6);
INSERT INTO matches (player1, player2, winner) VALUES (9, 1, 1);
INSERT INTO matches (player1, player2, winner) VALUES (10, 2, 2);
INSERT INTO matches (player1, player2, winner) VALUES (3, 5, 3);
INSERT INTO matches (player1, player2, winner) VALUES (4, 6, 6);
INSERT INTO matches (player1, player2, winner) VALUES (7, 9, 9);
INSERT INTO matches (player1, player2, winner) VALUES (8, 10, 8);
INSERT INTO matches (player1, player2, winner) VALUES (11, 1, 11);
INSERT INTO matches (player1, player2, winner) VALUES (1, 12, 12);
INSERT INTO matches (player1, player2, winner) VALUES (13, 1, 1);